# This study is used as an example (but realistic) workflow a user can follow to see how NLP data
# flows through the Cumulus pipeline.

study_prefix = "example_nlp"

[[stages.example_build]]
description = "Range calculation"
files = [
    "calculate_ranges.py",
]
