study_prefix = "discovery"

[[stages.build_discovery]]
description= "code detection"
files = [
    "code_detection.py",
]
action_type="parallel"
[[stages.build_discovery]]
description = "code union"
files= [
    "code_union.py"
]
action_type="parallel"
[[stages.build_discovery]]
description = "temp data cleanup"
files = [
    "cleanup_tmp.py"
]
action_type="parallel"


[export_config]
count_list = [
    "discovery__code_sources",
]
