study_prefix = "discovery"

[file_config.file_names]
"code detection" = [
    "code_detection.py",
]
"temp data cleanup" = [
    "cleanup_tmp.py"
]


[export_config]
count_list = [
    "discovery__code_sources",
]
